Chapter 06 - Scriptgit status
budacom/programmingbitcoin-ruby pull request #6
Opened 2022-06-10 18:59 UTC by fedetaladriz

WIP

2022-06-17 12:01 UTC, educifuentes requested changes
Agregue unas sugerencias para hacer mas leibles los Op codes

2022-06-17 12:01 UTC, educifuentes commented on lib/bitcoin/op.rb
> +require 'ecc/signature'
Los cambiaría a `require_relative` para mantener la consistencia

2022-06-17 12:01 UTC, educifuentes commented on lib/encoding_helper.rb
> +
[SUG] Agregaria un `encode_number` como se hace en el libro para usar en `Op`
Podría ser esto inicialmente y después lo vamos modificando para los demás casos de num:
```
def encode_number(num)
    return '' if num.zero?

    int_to_little_endian(num, 1)
  end
```

2022-06-17 12:01 UTC, educifuentes commented on lib/bitcoin/op.rb
> +      stack << ''
[SUG] De agregar encode_number  lo aplicaria: `stack << encode_number(0)`

2022-06-17 12:01 UTC, educifuentes commented on lib/bitcoin/op.rb
> +               end
Aqui también lo aplicaría: 
```
stack << (point.verify(z, sig) ? encode_number(1) : encode_number(0))
```

2022-06-17 16:21 UTC, fedetaladriz commented on lib/encoding_helper.rb
> +
Buena, lo agrego!

2022-06-17 16:51 UTC, fedetaladriz commented on lib/bitcoin/op.rb
> +require 'ecc/signature'
Si, me gustaba mas `require`, pero leyendo en internet veo que este se usa solo para dependencias externas. 
Lo cambio

2022-06-17 18:34 UTC, jgmontoya reviewed
Buena! Dejo algunos comentarios :D

2022-06-17 18:34 UTC, jgmontoya commented on lib/bitcoin/op.rb
> +               end
Esto podría ser one-liner con un ternario:

```ruby
  stack << (point.verify(z, sig) ? int_to_little_endian(1, 1) : '')
```

(necesitai el paréntesis eso sí porque si no creo que considerará `stack << point.verify(z, sig)` como la condición del ternario (agregará `point.verify(z, sig)` al stack)

2022-06-17 18:34 UTC, jgmontoya commented on lib/bitcoin/op.rb
> +      0 => 'OP_0', # implemented
Creo que no soy muy fan de este comentario, al final igual ya está acá mismo el si está implementado o no

2022-06-17 18:34 UTC, jgmontoya commented on spec/bitcoin/op_spec.rb
> +  # rubocop:disable Style/BlockDelimiters
No creo que sea necesario desabilitar esta regla, lo podemos dejar con { } nomás o no?

2022-06-17 18:34 UTC, jgmontoya commented on lib/bitcoin/script.rb
> +      io = BitcoinDataIO(_io)
No es taan relevante pero creo que puede ser un poco confuso el nombre `_io`, como que me da la sensación de que no se usará. Quizás algún nombre como "byte_string" o "byte_stream" o algo así?

2022-06-17 18:34 UTC, jgmontoya commented on lib/bitcoin/script.rb
> +            return false
Esto puede quedar 1-liner

```ruby
return false unless execute_operation(cmd, cmds, stack, altstack, z)
```

2022-06-17 18:34 UTC, jgmontoya commented on lib/bitcoin/script.rb
> +      true
No sé si me convence tanto (quizás es más legible como está) pero se podría dejar como:

```ruby
!stack.empty? && !stack.pop.empty?
```

2022-06-17 18:34 UTC, jgmontoya commented on lib/bitcoin/script.rb
> +        end
1-liner:

```ruby
cmd.is_a? Integer ? int_to_little_endian(cmd, 1) : serialized_element_prefix(cmd) + cmd
```

2022-06-17 18:34 UTC, jgmontoya commented on lib/encoding_helper.rb
> +# encoding: ascii-8bit
¿Por qué es necesario esto?

2022-06-17 18:34 UTC, jgmontoya commented on spec/encoding_helper_spec.rb
> +# encoding: ascii-8bit
Lo mismo acá

2022-06-17 18:41 UTC, fedetaladriz commented on spec/bitcoin/op_spec.rb
> +  # rubocop:disable Style/BlockDelimiters
Me estaba alegando si lo hacía con `{ }`
<img width="996" alt="Captura de Pantalla 2022-06-17 a la(s) 14 41 01" src="https://user-images.githubusercontent.com/26395403/174358667-0dd2d055-5b68-45de-86f1-15b48081ad8f.png">
:

2022-06-17 18:44 UTC, fedetaladriz commented on lib/bitcoin/script.rb
> +      io = BitcoinDataIO(_io)
Aquí me basé en la [implementación](https://github.com/budacom/programmingbitcoin-ruby/blob/a546864fea04d948c6fcddeb201fa6ef10308606/lib/bitcoin/tx.rb#L21:L22) de `Tx`. He visto en varias partes que se prefija con `_` cuando hay conflicto entre nombres de variables

2022-06-17 19:02 UTC, jgmontoya commented on spec/bitcoin/op_spec.rb
> +  # rubocop:disable Style/BlockDelimiters
Ohh que raro eso 🤔

2022-06-17 20:55 UTC, fedetaladriz commented on lib/bitcoin/script.rb
> +      true
Creo que siempre es mas legible evitando las negaciones 🤔

2022-06-17 21:20 UTC, fedetaladriz commented on lib/bitcoin/script.rb
> +        end
Buena, lo cambio. Detallito acá: la llama de `is_a` tiene que ir con parentesis: 
```ruby
cmd.is_a?(Integer) ? int_to_little_endian(cmd, 1) : serialized_element_prefix(cmd) + cmd
```

2022-06-17 23:31 UTC, jgmontoya approved these changes
¿Por qué cambiaste muchas comillas de simples a dobles en `spec/bitcoin/script_spec.rb`?

2022-06-18 00:53 UTC, fedetaladriz commented
> ¿Por qué cambiaste muchas comillas de simples a dobles en spec/bitcoin/script_spec.rb?

Porque en ese archivo había algunos test con comillas simples y otros con dobles

2022-06-18 15:50 UTC, merged